cargo-features = ["edition2021"]

[package]
name = "manticore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
rustyline = "9.1.1"
colored = "2.0.0"
dym = "1.0.1"
